### ISSUE TITLE
Channel switch needs 2 clicks

### ISSUE THREAD

**Issue by futurefounder** [futurefounder/thaiteewee#2]
At the moment the white noise is shown when a channel change is clicked.

` {switchChannel ? (
        <div>
          <div className="video-background">
            <div className="video-foreground">{preloadedPlyr}</div>
          </div>
        </div>
      ) : (
        <div></div>
      )}
    </div>`

Then, the user has to click again to switch a channel.

The white noise should only be shown for about .5 -1 second before switching to a new channel

**Comment by milo-** [comment]
I think you mentioned it on the call, but using a setTimeout in the control function to set the switchChannel value after 500/1000ms should work!

**Comment by futurefounder** [comment]
Thanks! 
Issue is [solved](https://github.com/futurefounder/thaiteewee/commit/ea810a1b8c95aa629d88f73276a438494bdb4a9d)
